name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DEV OPS E-LEARNING

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Start Docker services
        run: docker compose up -d

      - name: Wait for containers to be ready
        run: sleep 20

      - name: Build project
        run: ./gradlew build

      - name: Run tests (verbose)
        run: ./gradlew test --stacktrace --info

      - name: Stop Docker services
        run: docker compose down
