name: Generate PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-doc:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DEV OPS E-LEARNING

    steps:
      - uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Generate PDF
        run: pandoc docs/report.md -o docs/report.pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: DEV OPS E-LEARNING/docs/report.pdf
